name: Deploy to AWS IAM

on:
  push:
    branches:
      - main  # Runs this workflow when code is pushed to 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Run cleanup
        run: bash scripts/clean_up.sh

      - name: Run deployment scripts
        run: |
          bash scripts/create_vpc_create_subnets.sh
          bash scripts/create_iam_groups.sh
          bash scripts/add_users_to_groups.sh
          bash scripts/add_iam_policy.sh

      - name: Final cleanup scripts
        run: bash scripts/clean_up.sh
        
